<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { getResourceDetail, listResources, recordResourceInteraction } from '../api/resource';
import ResourceDetailRenderer from '../components/ResourceDetailRenderer.vue';
import DfsTraversalVisualizer from '../components/resource/DfsTraversalVisualizer.vue';
import SplitText from '../components/SplitText.vue';
import type { ResourceCard } from '../types';
import type { ResourceDetail } from '@/types/api';

type ResourceCategory = { type: ResourceCard['type']; label: string; eyebrow: string; description: string; icon: string; gradient: string; glow: string };
const CATEGORY_ORDER: ResourceCategory[] = [
  { type: 'lecture', label: '个性化讲义', eyebrow: '理解与复习', description: '把课程知识整理成可阅读、可回看的个性化讲义。', icon: '▤', gradient: 'linear-gradient(135deg, rgba(34,154,133,.92), rgba(111,207,185,.55))', glow: 'rgba(34,154,133,.3)' },
  { type: 'mindmap', label: '知识思维导图', eyebrow: '结构与关联', description: '从知识点关系出发，建立清晰的学习地图。', icon: '⌘', gradient: 'linear-gradient(135deg, rgba(83,111,205,.92), rgba(149,170,255,.55))', glow: 'rgba(83,111,205,.3)' },
  { type: 'quiz', label: '分层练习题', eyebrow: '练习与诊断', description: '用分层练习发现薄弱点，并把结果回流到路径。', icon: '✓', gradient: 'linear-gradient(135deg, rgba(230,150,72,.96), rgba(255,206,124,.58))', glow: 'rgba(230,150,72,.3)' },
  { type: 'codelab', label: '代码实验', eyebrow: '实践与迁移', description: '通过代码实验把概念变成可运行的步骤。', icon: '</>', gradient: 'linear-gradient(135deg, rgba(176,91,132,.94), rgba(239,161,194,.58))', glow: 'rgba(176,91,132,.3)' },
  { type: 'flowchart', label: '流程图', eyebrow: '流程与决策', description: '把复杂流程压缩成可追踪的判断节点。', icon: '↗', gradient: 'linear-gradient(135deg, rgba(111,102,181,.94), rgba(193,180,255,.58))', glow: 'rgba(111,102,181,.3)' },
  { type: 'reading', label: '拓展阅读', eyebrow: '延伸与拓展', description: '基于课程证据补充当前阶段的延伸阅读。', icon: '◫', gradient: 'linear-gradient(135deg, rgba(57,132,176,.94), rgba(143,211,244,.58))', glow: 'rgba(57,132,176,.3)' },
];

const resources = ref<ResourceCard[]>([]); const selected = ref<ResourceDetail | null>(null); const activeCategoryIndex = ref(0); const loading = ref(true); const detailLoading = ref(false); const errorMessage = ref(''); const progress = ref(0); const rating = ref(0); const interactionNote = ref('');
const categoryResourceCount = computed(() => { const counts = new Map<ResourceCard['type'], number>(); resources.value.forEach((resource) => counts.set(resource.type, (counts.get(resource.type) || 0) + 1)); return counts; });
const activeCategory = computed(() => CATEGORY_ORDER[activeCategoryIndex.value]); const activeResources = computed(() => resources.value.filter((resource) => resource.type === activeCategory.value.type)); const activeResourceNames = computed(() => activeResources.value.map((resource) => resource.title)); const activeResourcePreview = computed(() => activeResourceNames.value.slice(0, 3)); const activeResourceRemainder = computed(() => Math.max(activeResourceNames.value.length - activeResourcePreview.value.length, 0)); const categoryCount = (type: ResourceCard['type']) => categoryResourceCount.value.get(type) || 0;
const showDfsVisualizer = computed(() => {
  const detail = selected.value;
  const searchable = [detail?.title, detail?.summary, detail?.content, ...(detail?.knowledge_points ?? [])].filter(Boolean).join(' ');
  return /(?:\bDFS\b|深度优先(?:搜索|遍历)?)/i.test(searchable);
});
const isLectureResource = computed(() => {
  const type = selected.value?.resource_type || selected.value?.type;
  return type === 'lecture';
});
const visibleCategoryEntries = computed(() => [-1, 0, 1, 2].map((offset) => { const index = (activeCategoryIndex.value + offset + CATEGORY_ORDER.length) % CATEGORY_ORDER.length; return { category: CATEGORY_ORDER[index], index }; }));
const setCategory = (index: number) => { activeCategoryIndex.value = (index + CATEGORY_ORDER.length) % CATEGORY_ORDER.length; selected.value = null; interactionNote.value = ''; }; const shiftCategory = (delta: number) => setCategory(activeCategoryIndex.value + delta);
const loadResources = async () => { loading.value = true; errorMessage.value = ''; try { const data = await listResources({ page: 1, size: 50 }); resources.value = data.items.filter((resource) => resource.type !== 'animation_script'); const firstPopulated = CATEGORY_ORDER.findIndex((category) => categoryCount(category.type) > 0); if (firstPopulated >= 0) activeCategoryIndex.value = firstPopulated; } catch (error) { errorMessage.value = error instanceof Error ? error.message : '资源列表加载失败'; } finally { loading.value = false; } };
const openResource = async (resource: ResourceCard) => { detailLoading.value = true; interactionNote.value = ''; try { selected.value = await getResourceDetail(resource.id); const state = await recordResourceInteraction(resource.id, { action: 'view', progressPercent: progress.value }); progress.value = state.progress_percent ?? 0; rating.value = state.rating ?? 0; } catch (error) { errorMessage.value = error instanceof Error ? error.message : '资源详情加载失败'; } finally { detailLoading.value = false; } };
const updateProgress = async (value: number) => { if (!selected.value) return; progress.value = value; const action = value >= 100 ? 'complete' : 'start'; const state = await recordResourceInteraction(selected.value.resource_id || String(selected.value.id), { action, progressPercent: value }); const mastery = state.learning_update?.mastery_updates?.[0]; interactionNote.value = mastery ? `${mastery.knowledge_point} 掌握度 ${mastery.previous_score}% → ${mastery.mastery_score}%` : value >= 100 ? '已完成，本次学习行为已记录；重复提交不会重复加权。' : `学习进度已记录为 ${value}%`; };
const rateResource = async (value: number) => { if (!selected.value) return; rating.value = value; await recordResourceInteraction(selected.value.resource_id || String(selected.value.id), { action: 'rate', rating: value, progressPercent: progress.value }); interactionNote.value = `已记录 ${value} 星评价。`; }; onMounted(loadResources);
</script>

<template>
  <section class="resource-library ai-page-bg page-enter">
    <header class="resource-library__head"><div><span>PERSONALIZED LIBRARY / 资源分类浏览</span><SplitText tag="h1" text="你的学习资源空间" /><p>先按学习目的选择资源类型，再进入对应的资源包。每一类内容都保留画像依据、课程证据和安全审查结果。</p></div><div class="library-total" aria-label="资源总量"><strong>{{ resources.length }}</strong><span>个资源包</span></div></header>
    <p v-if="loading" class="library-state">正在同步资源库...</p><p v-else-if="errorMessage" class="library-state error-line">{{ errorMessage }}</p><p v-else-if="!resources.length" class="library-state">暂无资源，请先在资源生成页面创建个性化资源包。</p>
    <template v-else>
      <section class="category-stage" aria-label="资源类别选择"><button class="category-arrow" type="button" aria-label="上一个资源类别" @click="shiftCategory(-1)">‹</button><div class="category-rail"><button v-for="entry in visibleCategoryEntries" :key="entry.category.type" type="button" class="category-card" :class="{ active: entry.index === activeCategoryIndex, empty: categoryCount(entry.category.type) === 0 }" :style="{ '--category-gradient': entry.category.gradient, '--category-glow': entry.category.glow }" @click="setCategory(entry.index)"><div class="category-card__top"><b>{{ entry.category.icon }}</b></div><h2>{{ entry.category.label }}</h2></button></div><button class="category-arrow" type="button" aria-label="下一个资源类别" @click="shiftCategory(1)">›</button></section>
      <section class="category-caption" :style="{ '--category-glow': activeCategory.glow }"><div><span>当前分类 / {{ activeCategory.eyebrow }}</span><h2>{{ activeCategory.label }} <small>{{ categoryCount(activeCategory.type) }} 个资源包</small></h2><p>{{ activeCategory.description }}</p></div><div v-if="activeResourcePreview.length" class="category-caption__packs"><span>这里有：</span><strong v-for="name in activeResourcePreview" :key="name">{{ name }}</strong><em v-if="activeResourceRemainder">+{{ activeResourceRemainder }} 个</em></div><div v-else class="category-caption__empty">这个类别暂时还没有资源，去“资源生成”创建一份吧。</div></section>
      <section class="category-focus" :style="{ '--category-glow': activeCategory.glow }"><header class="category-focus__head"><div><span>EXPLORE {{ activeCategory.label.toUpperCase() }}</span><h2>{{ activeCategory.label }} 资源包</h2></div><small>点击任意资源包查看完整内容、课程依据和学习反馈</small></header><div v-if="activeResources.length" class="resource-pack-grid"><button v-for="resource in activeResources" :key="resource.id" type="button" class="resource-pack" @click="openResource(resource)"><div class="resource-pack__visual"><span>{{ activeCategory.label }}</span><b>{{ activeCategory.icon }}</b></div><div class="resource-pack__body"><div class="resource-pack__meta"><span>{{ resource.difficulty || '个性化' }}</span><span v-if="resource.minutes">{{ resource.minutes }} 分钟</span></div><h3>{{ resource.title }}</h3><p>{{ resource.subtitle }}</p><small>{{ resource.tags.slice(0, 2).join(' · ') }}</small></div><i>查看资源包 →</i></button></div><div v-else class="category-empty"><b>{{ activeCategory.icon }}</b><h3>还没有 {{ activeCategory.label }} 资源</h3><p>生成资源时选择 {{ activeCategory.label }}，它会出现在这里。</p></div></section>
    </template>
    <div v-if="selected || detailLoading" class="resource-dialog" role="dialog" aria-modal="true" @click.self="selected = null"><article class="resource-reader"><button class="resource-reader__close" type="button" aria-label="关闭资源详情" @click="selected = null">×</button><p v-if="detailLoading">正在读取资源详情...</p><template v-else-if="selected"><header><span>{{ selected.resource_type || selected.type }} · {{ selected.difficulty }}</span><h1>{{ selected.title }}</h1><p>{{ selected.personalized_reason || selected.summary }}</p></header><div class="resource-reader__meta"><span>预计 {{ selected.estimated_minutes || '—' }} 分钟</span><span>Safety {{ selected.safety.passed ? '通过' : '需复核' }}</span><span>置信度 {{ Math.round(selected.safety.confidence * 100) }}%</span></div><DfsTraversalVisualizer v-if="showDfsVisualizer && isLectureResource" />\n<ResourceDetailRenderer :detail="selected" /><section v-if="showDfsVisualizer && !isLectureResource" class="dfs-support-section"><header><span>辅助理解</span><h2>图结构与递归栈同步演示</h2><p>先完成当前类别的主要内容，再通过交互图解核对 DFS 的访问、入栈与回溯过程。</p></header><DfsTraversalVisualizer /></section><section class="evidence-list"><h2>课程知识依据</h2><article v-for="item in selected.evidence" :key="item.chunk_id || item.chunkId"><strong>{{ item.title }}</strong><p>{{ item.content }}</p><small>{{ item.source }} · {{ Math.round(item.score * 100) }}%</small></article></section><footer class="learning-actions"><div><strong>学习进度</strong><button v-for="value in [25, 50, 75, 100]" :key="value" :class="{ active: progress === value }" @click="updateProgress(value)">{{ value }}%</button></div><div><strong>资源评价</strong><button v-for="value in 5" :key="value" :class="{ active: rating >= value }" @click="rateResource(value)">★</button></div><p>{{ interactionNote }}</p></footer></template></article></div>
  </section>
</template>

<style scoped>
.resource-library{min-height:calc(100vh - 72px);padding:48px clamp(18px,5vw,84px) 78px;color:var(--color-ink);overflow:hidden}.resource-library__head{display:flex;justify-content:space-between;gap:24px;align-items:end;margin-bottom:34px}.resource-library__head>div:first-child{max-width:780px}.resource-library__head span,.category-focus__head>div>span,.category-caption>div:first-child>span{color:var(--color-primary);font-weight:900;font-size:11px;letter-spacing:.13em}.resource-library__head h1{font-size:clamp(36px,5vw,62px);margin:10px 0 12px;letter-spacing:-.05em}.resource-library__head p{max-width:720px;color:rgba(31,54,49,.68);line-height:1.8}.library-total{width:132px;height:132px;flex:0 0 132px;display:flex;flex-direction:column;justify-content:center;align-items:center;gap:2px;border:1px solid rgba(255,255,255,.72);border-radius:24px;white-space:nowrap;color:rgba(255,255,255,.9);background:linear-gradient(145deg,rgba(91,119,187,.92),rgba(151,176,255,.52));box-shadow:0 20px 42px -24px rgba(83,111,205,.52),inset 0 1px rgba(255,255,255,.58)}.library-total strong{font-size:50px;line-height:1;color:#fff;letter-spacing:-.08em}.library-total span{font-size:17px;line-height:1.2;font-weight:800;color:rgba(255,255,255,.95)}.library-state{padding:42px 0;color:rgba(31,54,49,.62)}.error-line{color:#df5b45}
.category-stage{position:relative;display:flex;align-items:stretch;gap:16px;margin:18px auto;max-width:1420px}.category-rail{display:grid;grid-template-columns:repeat(4,minmax(210px,1fr));gap:18px;flex:1;min-width:0}.category-card{min-height:294px;text-align:left;border:1px solid rgba(255,255,255,.52);border-radius:30px;padding:25px;color:#fff;background:var(--category-gradient);box-shadow:0 22px 42px -24px var(--category-glow),inset 0 1px rgba(255,255,255,.48);cursor:pointer;transition:transform .35s ease,box-shadow .35s ease,filter .35s ease,opacity .35s ease;display:flex;flex-direction:column}.category-card:hover,.category-card.active{transform:translateY(-9px) scale(1.015);box-shadow:0 32px 58px -24px var(--category-glow),inset 0 1px rgba(255,255,255,.68)}.category-card:not(.active){filter:saturate(.72);opacity:.78}.category-card.empty{opacity:.46}.category-card__top{display:flex;align-items:center;justify-content:flex-end}.category-card__top b{display:grid;place-items:center;width:58px;height:58px;border:1px solid rgba(255,255,255,.45);border-radius:18px;font-size:29px;letter-spacing:-.12em}.category-card h2{font-size:clamp(28px,3vw,40px);letter-spacing:-.055em;margin:auto 0 0;color:#fff}.category-arrow{flex:0 0 48px;align-self:center;width:48px;height:48px;border:1px solid rgba(31,54,49,.13);border-radius:50%;background:rgba(255,255,255,.74);color:var(--color-ink);font-size:34px;line-height:1;cursor:pointer;box-shadow:0 8px 22px rgba(31,54,49,.08);transition:transform .2s ease,background .2s ease}.category-arrow:hover{transform:scale(1.08);background:#fff}
.category-caption{display:flex;justify-content:space-between;gap:30px;align-items:center;max-width:1160px;margin:0 auto 20px;padding:20px 24px;border:1px solid rgba(31,54,49,.1);border-radius:21px;background:linear-gradient(110deg,rgba(255,255,255,.7),rgba(255,255,255,.4));box-shadow:0 15px 45px -35px var(--category-glow)}.category-caption h2{margin:6px 0 3px;font-size:25px;letter-spacing:-.035em}.category-caption h2 small{font-size:12px;color:rgba(31,54,49,.5);font-weight:700;margin-left:8px}.category-caption p{margin:0;color:rgba(31,54,49,.62);font-size:13px}.category-caption__packs{display:flex;align-items:center;justify-content:flex-end;flex-wrap:wrap;gap:7px;max-width:560px}.category-caption__packs>span{color:rgba(31,54,49,.5);font-size:12px}.category-caption__packs strong,.category-caption__packs em{border-radius:999px;padding:8px 11px;background:rgba(255,255,255,.8);border:1px solid rgba(31,54,49,.08);font-size:11px;font-style:normal;font-weight:800;white-space:nowrap}.category-caption__packs em{color:var(--color-primary);background:rgba(0,121,102,.07)}.category-caption__empty{max-width:420px;color:rgba(31,54,49,.52);font-size:12px;line-height:1.6}
.category-focus{width:min(88%,1180px);margin:0 auto;padding:28px 30px 32px;border-radius:30px;background:rgba(255,255,255,.66);border:1px solid rgba(255,255,255,.9);box-shadow:0 26px 65px -42px var(--category-glow),0 1px 0 rgba(255,255,255,.7) inset}.category-focus__head{display:flex;justify-content:space-between;align-items:end;gap:20px;border-bottom:1px solid rgba(31,54,49,.09);padding-bottom:20px;margin-bottom:22px}.category-focus__head h2{font-size:31px;margin:7px 0 0;letter-spacing:-.05em}.category-focus__head>small{color:rgba(31,54,49,.55);font-size:12px}.resource-pack-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:17px}.resource-pack{text-align:left;position:relative;overflow:hidden;border:1px solid rgba(31,54,49,.1);border-radius:20px;background:rgba(255,255,255,.84);padding:0;cursor:pointer;color:inherit;box-shadow:0 14px 32px -28px rgba(31,54,49,.55);transition:transform .3s ease,box-shadow .3s ease}.resource-pack:hover{transform:translateY(-5px);box-shadow:0 22px 38px -25px var(--category-glow)}.resource-pack__visual{height:105px;padding:17px 18px;display:flex;justify-content:space-between;align-items:flex-start;color:#fff;background:var(--category-gradient)}.resource-pack__visual span{font-size:10px;font-weight:900;letter-spacing:.1em;text-transform:uppercase}.resource-pack__visual b{font-size:28px;font-weight:500;opacity:.8}.resource-pack__body{padding:18px 18px 15px}.resource-pack__meta{display:flex;gap:7px;color:rgba(31,54,49,.52);font-size:10px;text-transform:uppercase;letter-spacing:.08em}.resource-pack h3{font-size:17px;line-height:1.35;margin:10px 0 8px}.resource-pack p{font-size:12px;line-height:1.6;color:rgba(31,54,49,.64);min-height:39px;margin:0 0 10px}.resource-pack small{color:var(--color-primary);font-size:11px}.resource-pack>i{display:block;padding:0 18px 17px;color:var(--color-primary);font-size:11px;font-style:normal;font-weight:900}.category-empty{text-align:center;padding:58px 20px;color:rgba(31,54,49,.58)}.category-empty b{display:grid;place-items:center;width:58px;height:58px;border-radius:20px;margin:0 auto 14px;background:rgba(0,121,102,.08);color:var(--color-primary);font-size:27px}.category-empty h3{margin:0 0 8px;color:var(--color-ink)}.category-empty p{margin:0;font-size:13px}
.dfs-support-section{display:grid;gap:14px;margin-top:8px;border-top:1px solid rgba(31,54,49,.1);padding-top:22px}.dfs-support-section>header{display:grid;gap:5px}.dfs-support-section>header span{color:var(--color-primary);font-size:11px;font-weight:900;letter-spacing:.12em}.dfs-support-section>header h2{margin:0;font-size:20px}.dfs-support-section>header p{margin:0;color:rgba(31,54,49,.64);font-size:13px;line-height:1.65}.resource-dialog{position:fixed;inset:0;z-index:100;background:rgba(18,34,30,.58);display:grid;place-items:center;padding:28px}.resource-reader{position:relative;width:min(980px,100%);max-height:92vh;overflow:auto;border-radius:22px;background:#fff;padding:42px;box-shadow:0 28px 80px rgba(0,0,0,.24)}.resource-reader__close{position:absolute;right:22px;top:16px;border:0;background:transparent;font-size:32px;cursor:pointer}.resource-reader header>span{color:var(--color-primary);font-weight:900}.resource-reader header h1{font-size:34px;margin:10px 0}.resource-reader header p{color:#b65d32;line-height:1.7}.resource-reader__meta{display:flex;gap:10px;flex-wrap:wrap;margin:20px 0}.resource-reader__meta span{border-radius:999px;background:rgba(0,121,102,.08);padding:8px 12px;font-size:13px;font-weight:800}.evidence-list{margin-top:36px;border-top:1px solid rgba(31,54,49,.1);padding-top:24px}.evidence-list article{border-left:3px solid var(--color-primary);background:rgba(0,121,102,.05);margin:12px 0;padding:14px 18px}.evidence-list p{line-height:1.7}.learning-actions{border-top:1px solid rgba(31,54,49,.1);display:grid;gap:14px;margin-top:28px;padding-top:22px}.learning-actions div{display:flex;align-items:center;gap:9px}.learning-actions strong{min-width:90px}.learning-actions button{border:1px solid rgba(0,121,102,.18);border-radius:9px;background:#fff;color:var(--color-primary);cursor:pointer;padding:8px 11px}.learning-actions button.active{background:var(--color-primary);color:#fff}.learning-actions p{color:var(--color-primary);margin:0}
@media(max-width:1180px){.category-rail{grid-template-columns:repeat(4,minmax(175px,1fr));overflow:hidden}.resource-pack-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:760px){.resource-library{padding:32px 16px 56px}.resource-library__head{align-items:start;flex-direction:column}.library-total{width:116px;height:116px;flex-basis:116px;margin-top:-10px}.library-total strong{font-size:44px}.library-total span{font-size:15px}.category-stage{gap:6px}.category-arrow{flex-basis:34px;width:34px;height:34px;font-size:24px}.category-rail{display:block}.category-card{display:none!important;min-height:230px}.category-card.active{display:flex!important}.category-caption{display:block;padding:18px;margin-bottom:14px}.category-caption__packs{justify-content:flex-start;margin-top:14px}.category-focus{width:100%;padding:22px 16px 24px;border-radius:23px}.category-focus__head{display:block}.category-focus__head>small{display:block;margin-top:12px}.resource-pack-grid{grid-template-columns:1fr}.resource-reader{padding:32px 22px}.resource-dialog{padding:10px}}
</style>
